# Generated by Django 5.2.12 on 2026-04-06 13:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoneypotEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this honeypot entry.', primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('api_key', 'API Key'), ('jwt_token', 'JWT Token'), ('db_url', 'Database URL'), ('private_key', 'Private Key'), ('oauth_token', 'OAuth Token'), ('decoy_password', 'Decoy Password')], help_text='Type of fake credential.', max_length=32)),
                ('provider', models.CharField(blank=True, default='', help_text='Simulated service provider (e.g. stripe, aws).', max_length=64)),
                ('fake_secret', models.TextField(help_text='The generated fake credential value.')),
                ('honeypot_id', models.UUIDField(help_text='Batch ID — groups all entries from a single generation run.')),
                ('generator', models.CharField(choices=[('ollama_llm', 'Ollama LLM'), ('transformers_llm', 'Transformers LLM'), ('fallback', 'Deterministic Fallback')], help_text='Which generation engine produced this entry.', max_length=32)),
                ('is_triggered', models.BooleanField(default=False, help_text='Set to True if this honeypot credential was accessed/used.')),
                ('triggered_at', models.DateTimeField(blank=True, help_text='When the honeypot was triggered.', null=True)),
                ('triggered_ip', models.GenericIPAddressField(blank=True, help_text='Source IP address of the trigger event.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User whose vault this honeypot protects.', on_delete=django.db.models.deletion.CASCADE, related_name='honeypot_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Honeypot Entry',
                'verbose_name_plural': 'Honeypot Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='idx_honeypot_user_cat'), models.Index(fields=['honeypot_id'], name='idx_honeypot_batch'), models.Index(fields=['is_triggered'], name='idx_honeypot_triggered')],
            },
        ),
    ]
